version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-197-239-115.compute-1.amazonaws.com
            port: '5432'
            database: d28uoiqn1ujfmr
            ssl: true
            user: xcsgowzavposdv
            password: 18df57b75363f71a06523c40f9eaf83d22f6ef644bb47b2b3e1412269245ae82
            migrations: true